# Generated by Django 4.2.7 on 2025-07-16 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='RUC debe tener exactamente 11 dígitos', regex='^\\d{11}$')])),
                ('business_name', models.CharField(max_length=500, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre Comercial')),
                ('address_type_code', models.CharField(default='0000', max_length=4)),
                ('address', models.CharField(max_length=500, verbose_name='Dirección')),
                ('district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('country_code', models.CharField(default='PE', max_length=2)),
                ('ubigeo', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_path', models.CharField(blank=True, max_length=500, null=True)),
                ('certificate_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('document_type', models.CharField(max_length=2)),
                ('document_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado a SUNAT'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('operation', models.CharField(max_length=50)),
                ('xml_file', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_file', models.CharField(blank=True, max_length=500, null=True)),
                ('cdr_file', models.CharField(blank=True, max_length=500, null=True)),
                ('sunat_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('sunat_response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sunat_response_description', models.TextField(blank=True, null=True)),
                ('processing_duration', models.PositiveIntegerField(blank=True, help_text='Duración en milisegundos', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Log de Documento',
                'verbose_name_plural': 'Logs de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Código del Producto')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('unit_code', models.CharField(choices=[('NIU', 'UNIDAD (BIENES)'), ('ZZ', 'UNIDAD (SERVICIOS)'), ('KGM', 'KILOGRAMO'), ('MTR', 'METRO'), ('LTR', 'LITRO')], default='NIU', max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('is_taxed', models.BooleanField(default=True, verbose_name='Afecto a IGV')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuito')),
                ('tax_category_code', models.CharField(default='S', max_length=10, verbose_name='Código de Categoría Tributaria')),
                ('tax_exemption_reason_code', models.CharField(blank=True, max_length=2, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('01', 'FACTURA'), ('03', 'BOLETA DE VENTA'), ('07', 'NOTA DE CREDITO'), ('08', 'NOTA DE DEBITO')], max_length=2)),
                ('series', models.CharField(max_length=4)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_series', to='core.company')),
            ],
            options={
                'verbose_name': 'Serie de Documento',
                'verbose_name_plural': 'Series de Documentos',
                'unique_together': {('company', 'document_type', 'series')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('0', 'DOC.TRIB.NO.DOM.SIN.RUC'), ('1', 'DNI'), ('4', 'CARNET DE EXTRANJERIA'), ('6', 'RUC'), ('7', 'PASAPORTE'), ('A', 'CEDULA DIPLOMATICA DE IDENTIDAD'), ('B', 'DOC.IDENT.PAIS.RESIDENCIA-NO.D'), ('C', 'TAX IDENTIFICATION NUMBER - TIN – DOC TRIB PP.NN'), ('D', 'IDENTIFICATION NUMBER - IN – DOC TRIB PP. JJ'), ('E', 'TAM- TARJETA ANDINA DE MIGRACION')], max_length=1)),
                ('document_number', models.CharField(max_length=15)),
                ('business_name', models.CharField(max_length=500, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre Comercial')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(default='PE', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('company', 'document_type', 'document_number')},
            },
        ),
    ]
