# ubl_converter/migrations/0001_initial.py
# Generated by Django 4.2.7 on 2025-07-16 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('document_type', models.CharField(choices=[('01', 'FACTURA'), ('03', 'BOLETA DE VENTA')], max_length=2)),
                ('series', models.CharField(max_length=4)),
                ('number', models.PositiveIntegerField()),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('currency_code', models.CharField(choices=[('PEN', 'NUEVOS SOLES'), ('USD', 'DOLARES AMERICANOS'), ('EUR', 'EUROS')], default='PEN', max_length=3)),
                ('operation_type_code', models.CharField(choices=[('0101', 'VENTA INTERNA'), ('0112', 'VENTA INTERNA - ANTICIPOS'), ('0200', 'EXPORTACIÓN'), ('0401', 'VENTA INTERNA NO DOMICILIADOS')], default='0101', max_length=4)),
                ('total_taxed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Operaciones Gravadas')),
                ('total_unaffected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Operaciones Inafectas')),
                ('total_exempt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Operaciones Exoneradas')),
                ('total_free_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Operaciones Gratuitas')),
                ('igv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IGV')),
                ('isc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ISC')),
                ('icbper_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ICBPER')),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descuentos')),
                ('total_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Cargos')),
                ('perception_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto de Percepción')),
                ('perception_base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base de Percepción')),
                ('perception_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de Percepción')),
                ('perception_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Percepción')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe Total')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado a SUNAT'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('xml_file', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_file', models.CharField(blank=True, max_length=500, null=True)),
                ('cdr_file', models.CharField(blank=True, max_length=500, null=True)),
                ('sunat_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('sunat_response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sunat_response_description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customer')),
            ],
            options={
                'verbose_name': 'Factura/Boleta',
                'verbose_name_plural': 'Facturas/Boletas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_means_code', models.CharField(choices=[('001', 'DEPÓSITO EN CUENTA'), ('002', 'GIRO'), ('003', 'TRANSFERENCIA DE FONDOS'), ('008', 'EFECTIVO, POR OPERACIONES EN LAS QUE NO EXISTE TRANSFERENCIA DE BIENES'), ('009', 'EFECTIVO, EN LOS DEMÁS CASOS')], max_length=3)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Pago')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ubl_converter.invoice')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(verbose_name='Número de Línea')),
                ('product_code', models.CharField(max_length=50, verbose_name='Código del Producto')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Cantidad')),
                ('unit_code', models.CharField(choices=[('NIU', 'UNIDAD (BIENES)'), ('ZZ', 'UNIDAD (SERVICIOS)'), ('KGM', 'KILOGRAMO'), ('MTR', 'METRO'), ('LTR', 'LITRO'), ('HUR', 'HORA')], default='NIU', max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Precio Unitario')),
                ('reference_price', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Precio de Referencia')),
                ('line_extension_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Venta')),
                ('tax_category_code', models.CharField(choices=[('S', 'GRAVADO - OPERACIÓN ONEROSA'), ('E', 'EXONERADO - OPERACIÓN ONEROSA'), ('O', 'INAFECTO - OPERACIÓN ONEROSA'), ('Z', 'GRATUITO')], default='S', max_length=1)),
                ('tax_exemption_reason_code', models.CharField(blank=True, max_length=2, null=True)),
                ('igv_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Tasa IGV %')),
                ('igv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto IGV')),
                ('isc_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa ISC %')),
                ('isc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto ISC')),
                ('icbper_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa ICBPER')),
                ('icbper_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto ICBPER')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='ubl_converter.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Facturas',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'document_type', 'series', 'number'), name='unique_invoice_per_company'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='unique_line_per_invoice'),
        ),
    ]