# Generated by Django 4.2.7 on 2025-07-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ubl_converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='unique_line_per_invoice',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'document_type', 'series', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceline',
            unique_together={('invoice', 'line_number')},
        ),
    ]
